name: pubspec_dart
version: 0.1.0
author: Matan Lurey <matan@lurey.org>
homepage: https://github.com/matanlurey/pubspec_dart
description: Inlines a pubspec file into Dart source code

environment:
  sdk: ">=1.21.0 <2.0.0"

dependencies:
  args: ">=0.13.4 <0.14.0"
  path: "^1.4.1"
  yaml: "^2.1.0"

dev_dependencies:
  test: "^0.12.18+1"

executable:
  build: build
