// Automatically generated by package:pubspec_dart
// Can be regenerated by running `pub global run pubspec_dart:build

/// Name of this package.
const name = 'pubspec_dart';

/// Version of "package:pubspec_dart".
const version = '0.1.0';
